let $CE1 := count(collection('ECRISCOL')//head[contains(text(), "CE1")])
let $CE2 := count(collection('ECRISCOL')//head[contains(text(), "CE2")])
let $CM1 := count(collection('ECRISCOL')//head[contains(text(), "CM1")])
let $CM2 := count(collection('ECRISCOL')//head[contains(text(), "CM2")])
let $SIX := count(collection('ECRISCOL')//head[contains(text(), "6EME")])
let $TROIS := count(collection('ECRISCOL')//head[contains(text(), "-3-")])
let $DEUX := count(collection('ECRISCOL')//head[contains(text(), "-2-")])
let $UNIV := count(collection('ECRISCOL')//head[contains(text(), "L1")])
return (concat("CE1 : ", $CE1), concat("CE2 : ", $CE2), concat("CM1 : ", $CM1), concat("CM2 : ", $CM2), concat("6ème : ", $SIX), concat("3ème : ", $TROIS), concat("2nde : ", $DEUX), concat("UNIV : ", $UNIV))